<div class="jm-masshead" <?php if(isset($config['background'])): ?> style="background-image: url(<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$config['background']; ?>)" <?php endif; ?>>
	<div class="main">
		<h3 class="ja-masshead-title"><span><?php echo $config['title']; ?></span></h3>
		<div class="ja-masshead-desc"><span><?php echo $config['description']; ?></span></div>
	</div>
</div>