<script src="<?php echo $this->getJsUrl().'magestore/instantsearch.js'; ?>" type="text/javascript"></script>
<form id="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
    <div class="form-search">
		<div id="instantsearch">
			<label for="search"><?php echo $this->__('Search:') ?></label>
			<div id="mi_header">
			<input id="search" type="text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo(Mage::registry('keyword')); ?>" class="input-text" />
			</div>
			<button type="submit" title="<?php echo $this->__('Search') ?>" class="button"><span><span><?php echo $this->__('Search') ?></span></span></button>
			<div id="search_autocomplete" class="search-autocomplete"></div>
			<script type="text/javascript">
			//<![CDATA[
				var searchForm = new Varien.searchForm('search_mini_form', 'search', '');
				searchForm.initAutocomplete('<?php echo $this->helper('catalogsearch')->getSuggestUrl() ?>', 'search_autocomplete');
			//]]>
			</script>	
		</div>		
    </div>
</form>
<div id="showProduct" style="display:none;">
	<div id="productContainer">
		<div class="head-notice">
			<h3 class="title left"><span id="searchTermkeyword">Search Product Instantly</span></h3>
			<a class="instantsearch-close right" href="javascript:void(0);" onclick="$('showProduct').hide(); return false;">Close</a>
		</div>
		<div id="mainProductWapper">
			<div id="mainProduct">
			
			</div>
		</div>
		<div id="moreProductsWapper">
			<div id="moreProducts">
				
			</div>
		</div>
		<div class="searchproduct-by-magestore" style="font-size: 10px">
            <a href="http://www.magestore.com"><?php echo $this->__('By Magestore'); ?></a>
			-
            <a href="http://www.magestore.com/magento-extensions.html/"><?php echo $this->__('Magento extensions');?></a>
        </div>
	</div>	
</div>	
<script type="text/javascript">
	var instantsearch = new Instantsearch(
        '<?php echo $this->getUrl('instantsearch/index/search') ?>',
		'<?php echo $this->getUrl('instantsearch/index/loadproduct') ?>',
		'<?php echo Mage::getStoreConfig('instantsearch/general/more_product_num') ?>',
		'search'
    );
	
	Event.observe('search', 'keyup', function(event){ 			
		instantsearch.search();		
	});
	//instantsearch.search();
	
</script>


