<?php if ($this->helper('sitemaster_checkout')->canPlaceOrder()): ?>
<span class="process loading" style="display:none">&nbsp;</span>
<button type="button" class="button btn-checkout btn btn-info" data-loading-text="<?php echo $this->__('Loading...') ?>" title="<?php echo $this->__('Place Order') ?>" id="place-order">
    <span><span><?php echo $this->__('Place Order') ?></span></span>
</button>
<?php endif ?>
