<div id="payment-methods" class="">
    <label class="tab-title"><?php echo $this->__('Choose Payment Method') ?>*</label>
    <div class="radio">
        <div id="payment-form" data-action="<?php echo $this->helper('sitemaster_checkout')->getUpdateUrl() ?>" data-update-sections="<?php echo $this->helper('sitemaster_checkout')->paymentDependentSections() ?>">
            <?php echo $this->getChildHtml('methods') ?>
        </div>
    </div>
    <div class="popup" id="payment-popup" style="display:none">
        <a href="#" class="popup-close">x</a>
        <div class="popup-heading"><h2><?php echo $this->__('Card Verification')?></h2></div>
        <div class="popup-content"></div>
    </div>
</div>
