<div class="block block-list catalog-block">
    <div class="block-content static-border">
        <p class="empty"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalog-left-1')->toHtml(); ?></p>
    </div>
</div>
<div class="block block-list catalog-block">
    <div class="block-content static-border">
        <p class="empty"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalog-left-2')->toHtml(); ?></p>
    </div>
</div>