
<script type="text/javascript">
/*
jQuery(document).ready(function($){
      if($("div.vertical-mega-menu #jm-megamenu").length > 0){
	  	$("#jm-megamenu").css("height","400px");
	  	megamenuinner = $('<div class="jm-megamenu-inner" />').append($("#jm-megamenu").html());
	  	$("#jm-megamenu").html("");
	  	$("#jm-megamenu").append(megamenuinner);
	  	window.categoryIScrol = new iScroll("jm-megamenu",{vScrollbar: true, useTransform: true,hScrollbar: false});
	  } 		
	  //}
})
*/
</script>
<?php
echo $menuoutput;

?>