<?php echo $this->getToolbarHtml(); ?>
<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $baseconfig =  Mage::helper("jmbasetheme")->getactiveprofile();
   
    if ($baseconfig) : 
            $productlistimagewidth = $baseconfig["productlistimagewidth"];
            $productlistimageheight = $baseconfig["productlistimageheight"];
            $productgriddeslenght = $baseconfig["productgriddeslenght"];
            $productgridimageheight = $baseconfig["productgridimageheight"];
            $productgridimagewidth = $baseconfig["productgridimagewidth"];
            $showlabel = $baseconfig["showlabel"];
        else :
            $productlistimagewidth = 180;
            $productlistimageheight = 180;
            $productgriddeslenght = 0;
            $productgridimageheight = 180;
            $productgridimagewidth = 180;
            $showlabel = 0;
        endif;
   
?>

<?php
  $randomid = rand();  
?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmproducts/js/jmproducts.js');?>"></script>
<script type="text/javascript">
   

    ja = jQuery.noConflict();
    ja(document).ready(function() {
    	  ja("ul#productsgrid"+<?php echo $randomid; ?>).jmproduct({
    	  	   qtytable:<?php echo $config['qtytable']; ?>,
    	  	   qtytableportrait:<?php echo $config['qtytableportrait']; ?>,
    	  	   istable:<?php echo $config['istable']; ?>,
    	  	   qtymobile:<?php echo $config['qtymobile']; ?>,
    	  	   qtymobileportrait:<?php echo $config['qtymobileportrait']; ?>,
    	  	   ismobile:<?php echo $config['ismobile']; ?>,
    	  });


	});
</script>

<div class="jm-product-list <?php echo $config['mode']; ?> clearfix">	
		<?php if($config['title']){?>
            <div class="internal-border">
         <div class="page-title category-title">
		<h1><?php echo $config['title']; ?></h1>
		<a href="<?php echo Mage::getBaseUrl()."jmproducts/viewall/index/type/".$config['mode']; ?>"><?php echo $this->__('view all') ?></a>
            </div>
            </div>
            <div class="internal-line"></div>
        <?php }; ?>
		
		<div class="listing-type-grid category-products">
			<?php $_collectionSize = $listall?$listall->count():0; ?>
			
			<?php $i = 0;
				$width = 100;
				// -- added by Duchh 15/12/2009
				$thumbnailw = $config['width'];
				$thumbnailh = $config['height'];
				$numberchar = $config['max'];

				if ($config['perrow']) $width = 100/$config['perrow'];
				$width = "style=\"width:{$width}%;\"";    
				$return = false;                
			?>							
			<?php if($_collectionSize){?>
				<ul class="products-grid" id="productsgrid<?php echo $randomid; ?>">
				<?php foreach ($listall->getItems() as $_product){ 
						$_rowCount = ceil($_collectionSize/$config['perrow']);
						if ($i%$config['perrow']==0) : $j++; endif;
						$i++;
						$product = Mage::getModel('catalog/product')->load($_product->getId());
						$attribute = $product->getResource()->getAttribute('label');
						if(is_object($attribute)){
						 
						    $_options= $attribute->getSource()->getAllOptions(true, true);
							foreach($_options as $option){
								  if ($option['value'] == $product->getData("label")){
									$class =  $option['label'];
								  }
							 }		   
							 $attdefaultvalue = $attribute->getDefaultValue();
							 $attributeValue = Mage::getModel('catalog/product')->load($_product->getId())->getlabel();
							 $attributeValueName = Mage::getModel('catalog/product')->load($_product->getId())->getAttributeText('label');
								 if(strlen($attributeValue) &&  ($attdefaultvalue !== $attributeValue)) { 
									 $labeltype = $class;   
									 $labelname = $attributeValueName;     
									 } 
									 else {
									 $labeltype = "";
							 } 
						}
				?> 
						<li class="item <?php if ($j==$_rowCount) : echo "item-row-last"; endif; ?> <?php if(($i-1)%$config['perrow']==0): ?> first<?php elseif($i%$config['perrow']==0): ?> last<?php endif; ?>" <?php echo $width;?>>
							<div class="inner">
								<div class="product-image">
									<a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
										<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($thumbnailw, $thumbnailh)->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
									</a>

									
									<?php if ($labeltype && $showlabel): ?>
											<span class="<?php echo $labeltype; ?>-label icon-label">
												<?php echo $labelname;	?>
											</span>		
										<?php endif; ?>
									<?php if($_product->isSaleable()){ ?>
										<button class="form-button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span><?php echo $this->helper("catalog")->__('Add to Cart') ?></span>
										</button>
										<?php } else { ?>
										<div class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock') ?></div>
									<?php } ?>
									<ul class="add-to-links">
										<?php if ($this->helper('wishlist')->isAllow()) : ?>
										<li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist">
											<?php echo $this->__('Wishlist') ?>
										</a></li>
										<?php endif; ?>
										<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
										<li>
											<a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Compare') ?></a></li>
										<?php endif; ?>
									</ul>
								</div>
								<div class="product-information">
									<h5 class="product-name">
										<a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $_product->getName() ?></a>
									</h5>
                                    <div class="oil-availability"><?php if ($_product->getAttributeText('emkost')) : ?><?php echo $this->__('Capacity') . " " . $_product->getAttributeText('emkost') . " " . $this->__('l.') ?><?php endif; ?></div>
                                    <?php echo $this->getReviewsSummaryHtml($_product, true, true)?>
									
									
									<?php echo $this->getPriceHtml($_product,true, '_jmproduct_' . rand()) ?>
									
									<?php if($numberchar) : ?>
										<p class="pdescription"><?php echo substr(nl2br(strlen($_product->getDescription()) > 10 ? $_product->getDescription() : $_product->getShortDescription()), 0, $numberchar).'...';?></p>
									<?php endif; ?>
									
								 </div>
							</div>
						</li>					
				<?php }?>		
				</ul>
				<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
			<?php }?>	
		</div>
</div>