<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Countdown
 * @version    1.0.3
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
?>
<div class="aw_countdown_timer" align="center">

    <div class="aw_countdown_days_container">
        <div class="aw_countdown_days">
            <div class="aw_countdown_spacer"></div>
            <span class="aw_countdown_days"></span>
        </div>
        <div><span class="aw_countdown_days_label"><?php echo $this->__('days'); ?></span></div>
    </div>

    <div class="aw_countdown_hours_container">
        <div class="aw_countdown_hours">
            <div class="aw_countdown_spacer"></div>
            <span class="aw_countdown_hours"></span>
        </div>
        <div><span class="aw_countdown_hours_label"><?php echo $this->__('hrs'); ?></span></div>
    </div>

    <div class="aw_countdown_separator">
        <div class="aw_countdown_separator_afterhours">:</div>
        <div class="aw_countdown_separator_afterhours_bottom"><span></span></div>
    </div>

    <div class="aw_countdown_minutes_container">
        <div class="aw_countdown_minutes">
            <div class="aw_countdown_spacer"></div>
            <span class="aw_countdown_minutes"></span>
        </div>
        <div><span class="aw_countdown_minutes_label"><?php echo $this->__('min'); ?></span></div>
    </div>

    <div class="aw_countdown_separator">
        <div class="aw_countdown_separator_afterminutes">:</div>
        <div class="aw_countdown_separator_afterminutes_bottom"><span></span></div>
    </div>

    <div class="aw_countdown_seconds_container">
        <div class="aw_countdown_seconds">
            <div class="aw_countdown_spacer"></div>
            <span class="aw_countdown_seconds"></span>
        </div>
        <div><span class="aw_countdown_seconds_label"><?php echo $this->__('sec'); ?></span></div>
    </div>
</div>

