<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Clickcheckout
 * @version    1.1.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
	?>
<div class="aw-clickcheckout-popup-shipping"">
    <h4 style="text-align: left;"><?php echo $this->__('Shipping method')?></h4>
    <?php if (!($_shippingRateGroups = $this->getShippingRates())): ?>
        <p><?php echo $this->__('Sorry, no quotes are available for this order at this time.') ?></p>
    <?php else: ?>
    <table class="sp-methods">
        <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>

                <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
            <tr> <td>
                            <?php if($_sole): ?>
                                 <?php Mage::helper('awclickcheckout')->setShipping($_rate->getCode());?>
                                 <input name="shipping_method" type="hidden" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"/>
                            <?php else: ?>
                                 <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio" onclick="oneClickCheckout.recalculateTotals('<?php echo Mage::getUrl('awclickcheckout/oneclick/validate');?>','<?php echo Mage::getUrl('checkout/onepage/saveOrder');?>'); oneClickCheckout.recalculateTotals('<?php echo Mage::getUrl('awclickcheckout/oneclick/validate');?>','<?php echo Mage::getUrl('checkout/onepage/saveOrder');?>');" />
                            <?php endif;?>
                            <label for="s_method_<?php echo $_rate->getCode() ?>">
                            <?php echo $_rate->getMethodTitle() ?>
                            <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                            <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                            <?php echo $_excl; ?>
                            <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                            <?php endif; ?>
                             (<?php echo $this->getCarrierName($code)?>)
                             </label>
               </td></tr>
                <?php endforeach; ?>

        <?php endforeach; ?>
    </table>
    <?php endif; ?>
</div>