<?php 

$divid = 'jm-contain-'.rand().rand().time();
$classid = 'jm-products-slider-content'.rand().rand().time();
$_collectionSize = 0;
if($listall) $_collectionSize = $listall->count() ;
if($configs['autorun']){
	$configs['autorun'] = $configs['delaytime'];
}


?>

<?php if($_collectionSize){?>


<?php if(!defined('JM_ADD_SKIN_PRODUCTS_SILDER')){?>

<?php if ($configs['use_scrollerbar']){ ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmproductsslider/js/jquery.customScroller-1.2.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmproductsslider/js/jquery.mousewheel.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmproductsslider/js/jquery.wresize.js') ?>"></script>
<?php }else{ ?>
<script type="text/javascript" src="<?php echo $this->getSkinUrl('joomlart/jmproductsslider/js/jcarousellite_1.0.1_custom.js') ?>"></script>
<?php } ?>

<?php  define('JM_ADD_SKIN_PRODUCTS_SILDER', true); ?>
<?php }?>

<script type="text/javascript">
	jQuery.noConflict();
<?php if ($configs['use_scrollerbar']){ ?>
	jQuery(window).bind("load", function(){
		jQuery(".<?php echo $classid; ?>").customScroller({width: <?php echo ($configs['itemwidth'])*($configs['number_items']);?>, height: <?php echo ($configs['itemheight']);?>});
	});
<?php }else{ ?>
	jQuery(document).ready(function($){
	    $("#<?php echo $divid?>").jCarouselLite({
	    	vertical: true,
			auto: <?php echo $configs['autorun']?>,
			speed: 			<?php echo $configs['animationtime']?>,
			visible: 		<?php echo $configs['number_items']?>,
			btnNext: "#jmmainwrap-<?php echo $divid?> .jm-next",
			btnPrev: "#jmmainwrap-<?php echo $divid?> .jm-prev",
			width: <?php echo $configs['number_items']*($configs['width']+10); ?>,
			width_img: <?php echo $configs['width']; ?>
		});
	});

	 
	
<?php } ?>	
</script>
<?php }?>

<div class="block jm-products-slider-listing" id="jmmainwrap-<?php echo $divid?>">
	<?php if(isset($configs['title']) && $configs['title']!=''){?>
	<div class="block-title"><strong><span><?php echo $configs['title']?> </span></strong></div>
	<?php if (!$configs['use_scrollerbar']){ ?>
		<div class="jm-prev"> <span> prev </span> </div>
		<div class="jm-next"> <span> next </span> </div>
		<?php }?>
	<?php }?>	

	<?php if($_collectionSize){?>
	
		  <div class="jm-products-slider-content clearfix block-content <?php echo $classid; ?>" > 
		    <div id="<?php echo $divid?>" class="jm-slider" style="overflow: hidden; width: <?php echo $_collectionSize*($configs['itemwidth']);?>px; float: left; left: 0 !important;">		    		    	
		      	<ul class="jm-slider-ul">
					<?php foreach ($listall->getItems() as $_product){ ?>
        			<li class="jm-slider-li" style="float: left;width:<?php echo $configs['itemwidth']; ?>px;height:<?php echo $configs['itemheight']; ?>px">
      					<div>
      						<div>
      							<a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
      								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->keepAspectRatio(TRUE)->resize($configs['width'], $configs['height'])->setWatermarkSize('30x10'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
      							</a>
      						</div>
      						
      						<div>
      							<a class="product-title" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>">
      								<span>
										<?php 
										if (strlen($_product->getName()) > 18) :
											echo substr($_product->getName(),0, 16).'...';
										else : 
											echo $_product->getName();
										endif;
										?>
									</span>
								</a>
								<span>
									<?php $gender = $_product->getData('gender');?>
									Gender: <?php if ($gender) echo($gender);?>
								</span>
								<span>
									<?php $releasedate = $_product->getData('releasedate');?>
									Release Date: <?php if ($releasedate) echo($releasedate);?>
								</span>
								
      							<?php if($configs['show_cart']){ ?>
									<?php if($_product->isSaleable()){ ?>
										<button class="button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
											<span>
												<?php if ($configs['show_price']) : ?>
													<?php echo $this->getPriceHtml($_product,true, '_jmslider') ?>
												<?php else:?>
													<?php echo $this->helper("catalog")->__('Buy') ?>
												<?php endif; ?>
											</span>
										</button>
									<?php } else { ?>
										<div class="out-of-stock"><?php echo $this->helper("catalog")->__('Out of stock') ?></div>
									<?php } ?>
								<?php } ?>
      							<span></span>
      						</div>
      					</div>
      				</li>
					<?php } ?> 
		      </ul>
		    </div>
		   </div>
	<?php } ?>
</div>