<?php $_manufacturersCollection = $this->getManufacturersCollection(); ?>
<?php $_columnCount = 8; ?>
<div>
    <div class="page-title">
        <h1><?php echo $this->__('Manufacturers') ?></h1>
    </div>
    <?php $i=0; foreach ($_manufacturersCollection as $_manufacturer): ?>
    <?php if ($i++%$_columnCount==0): ?>
    <ul class="products-grid first odd">
    <?php endif ?>
        <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
            <a href="<?php echo $this->getUrl('manufacturers' . '/' . $_manufacturer->getIdentifier()) ?>" title="<?php echo $_manufacturer->getManufacturer() ?>"><img alt="<?php echo $_manufacturer->getManufacturerLogo() ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'manufacturer' . '/' . $_manufacturer->getManufacturerLogo() ?>" width="75" height="75"></a>
            <h2><a href="<?php echo $this->getUrl('manufacturers' . '/' . $_manufacturer->getIdentifier()) ?>" title="<?php echo $_manufacturer->getManufacturer() ?>"><?php echo $_manufacturer->getManufacturer(); ?></a></h2>
        </li>
        <?php if ($i%$_columnCount==0 || $i==count($_manufacturersCollection)): ?>
    </ul>
    <?php endif ?>
    <?php endforeach; ?>
</div>
