<?php
/**
 * LiqPay Payment Module
 * 
 * NOTICE OF LICENSE
 * 
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * 
 * @category		Mage
 * @package			Mage_PBLiqPay
 * @version			1.0
 * @author			Ivan A. Zhivkov (http://twitter.com/iniplanet, http://electronov.com.ua)
 * @copyright		Copyright (c) 2010 Ivan A. Zhivkov
 * @license			http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * 
 * EXTENSION INFORMATION
 * 
 * Magento			Community Edition 1.3.2.4
 * LiqPay API		Click&Buy 1.2 (https://www.liqpay.com/?do=pages&p=cnb12)
 * Way of payment	Visa / MasterCard, or LiqPay
 * 
 * DONATIONS ^_^
 * 
 * If you will like, you can make a donation via LiqPay on my phone +380936991178
 * 
 */
?>
<fieldset class="form-list">
		<?php $_code=$this->getMethodCode() ?>
		<div id="payment_form_<?php echo $_code ?>" style="display: none;">
				<p style="margin-left: 20px;"><?php echo $this->__("Visa / MasterCard credit cards payment effected through the LiqPay payment system.") ?></p>
				<p style="margin-left: 20px;"><?php echo $this->__("Credit card's data input is making on the site's purchasing system. You will be redirected on the payment's page after confirmation of your order on the next step.") ?></p>
				<br />
		</div>
</fieldset>