
<form id="discount-coupon-form" action="<?php echo $this->getUrl('checkout/cart/couponPost') ?>" method="post">
    <div class="block-content">
        <?php // echo $this->__('Discount Codes') ?>
        <div class="registered-users">
            <?php // echo $this->__('Enter your coupon code if you have one.') ?>
            <input type="hidden" name="remove" id="remove-coupone" value="0" />
            <ul class="form-list">
                <li>
            <div class="input-box">
                <input class="input-text form-control" id="coupon_code" name="coupon_code" value="<?php echo $this->htmlEscape($this->getCouponCode()) ?>" />
            </div>
                </li>
            </ul>
            <div class="buttons-set">
                <button type="button" class="button" title="<?php echo $this->__('Apply Coupon') ?>" class="btn btn-defaul" name="apply" value="<?php echo $this->__('Apply Coupon') ?>"><span><span><?php echo $this->__('Apply Coupon') ?></span></span></button>
                <?php if(strlen($this->getCouponCode())): ?>
                    &nbsp; <button type="button" title="<?php echo $this->__('Cancel Coupon') ?>" class="button" name="cancel" value="<?php echo $this->__('Cancel Coupon') ?>"><span><span><?php echo $this->__('Cancel Coupon') ?></span></span></button>
                <?php endif;?>
            </div>
        </div>
    </div>
</form>
