<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>
<div class="jm-legal">
	<div class="footer-col-1"><?php echo "&copy;" . " " . date("Y") . " " .$this->getCopyright()  ?></div>
    <div class="footer-col-2"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('position-21')->toHtml(); ?></div>
    <div class="footer-col-3"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('position-22')->toHtml(); ?></div>
</div>





<!-- page loader test -->
<!-- <?php echo $total_time = round((microtime(TRUE)-$_SERVER['REQUEST_TIME_FLOAT']), 4); ?> -->