<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>	
<div class="main">
	<div class="inner clearfix">

        <!-- BEGIN: 1-COL LOGO-->
        <div class="top-logo">
		<h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" style="background-image: url(<?php echo $this->getLogoSrc() ?>);"><?php echo $this->getLogoAlt() ?></a></h1>
		<p class="no-display"><a href="#main"><strong><?php echo $this->__('Skip to Main Content') ?> &raquo;</strong></a></p>
        </div>
        <!-- BEGIN: 1-COL LOGO-->

        <!-- BEGIN: 2-COL SITE SEARCH & CONTACTS-->
        <div id="search-contacts">
            <div id="top-contacts"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('position-1')->toHtml(); ?></div>
			<div id="jm-search" class="has-toggle">
				<div class="btn-toggle search-toggle">
					<i class="fa fa-search"></i>
				</div>
				<div class="inner-toggle">
					<?php echo $this->getChildHtml('topSearch') ?>
				</div>
			</div>
            </div>

        <!-- END: 2-COL SITE SEARCH & CONTACTS -->

        <!-- BEGIN: 3-COL MY CART-->
        <div id="jm-mycart" class="has-toggle" >
            <div class="jmajmxloading">&nbsp;</div>
            <div class="btn-toggle mycart-toggle">
                <?php if(Mage::getSingleton('checkout/session')->getQuote()->getSubtotal() > 0 || Mage::getSingleton('checkout/session')->getQuote()->getSubtotal() > 1 ) { ?>
                    <i class="fa fa-shopping-cart"></i>
                    <a class="ico-shopping-cart" href="<?php echo Mage::getUrl("checkout/cart") ?>">
                        <span><?php echo $this->__("My Cart 1") ?></span>
                        <strong><?php echo Mage::getSingleton('checkout/session')->getQuote()->getItemsSummaryQty(); ?><?php echo $this->__(" items") ?></strong>
                    </a>
                <?php	} else { ?>
                    <i class="fa fa-shopping-cart"></i>
                    <a class="ico-shopping-cart" href="<?php echo Mage::getUrl("checkout/cart") ?>">
                        <span><?php echo $this->__("My Cart 1") ?></span>
                        <strong><?php echo Mage::getSingleton('checkout/session')->getQuote()->getItemsSummaryQty(); ?><?php echo $this->__(" item") ?></strong>
                    </a>
                <?php	} ?>
            </div>
            <div class="inner-toggle">
                <?php echo $this->getChildHtml('mycart') ?>
            </div>
        </div>
        <!-- END: 3-COL MY CART -->






        <!-- BEGIN: NAV -->
		<div id="mainnav-inner">
			<div id="jm-mainnav" class="has-toggle">
				<div class="btn-toggle menu-toggle" style="width: 119px">
					 <i class="fa fa-bars">&nbsp;</i>
				</div>				
				<div class="inner-toggle" id="jm-mainnav-inner">
					<?php echo $this->getChildHtml('topMenu') ?>
				</div>
			</div>
		</div>
        <!-- END: NAV -->










	</div>
</div>



