<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description: 
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 * 
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>	
<div class="main">
	<div class="inner clearfix">

        <!-- BEGIN: 1-COL LOGO-->
        <div class="top-logo">
		<h1 id="logo"><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" style="background-image: url(<?php echo $this->getLogoSrc() ?>);"><?php echo $this->getLogoAlt() ?></a></h1>
		<p class="no-display"><a href="#main"><strong><?php echo $this->__('Skip to Main Content') ?> &raquo;</strong></a></p>
        </div>
        <!-- BEGIN: 1-COL LOGO-->

        <!-- BEGIN: 2-COL SITE SEARCH & CONTACTS-->
        <div id="search-contacts">
            <div id="top-contacts"><?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('position-1')->toHtml(); ?></div>
			<div id="jm-search" class="has-toggle">
				<div class="btn-toggle search-toggle">
					<i class="fa fa-search"></i>
				</div>
				<div class="inner-toggle">
					<?php echo $this->getChildHtml('topSearch') ?>
				</div>
			</div>
            </div>

        <!-- END: 2-COL SITE SEARCH & CONTACTS -->

        <!-- BEGIN: MY CART-->
        <?php echo $this->getChildHtml('global_cart') ?>
        <!-- END: MY CART -->


        <!-- BEGIN: NAV -->
		<div id="mainnav-inner">
			<div id="jm-mainnav" class="has-toggle">
				<div class="btn-toggle menu-toggle" style="width: 119px">
					 <i class="fa fa-bars">&nbsp;</i>
				</div>				
				<div class="inner-toggle" id="jm-mainnav-inner">
					<?php echo $this->getChildHtml('topMenu') ?>
				</div>
			</div>
		</div>
        <!-- END: NAV -->










	</div>
</div>



<script>
    jQuery(function () {
        jQuery(window).bind('scroll', function() {
            var navHeight = 188;
            if (jQuery(window).scrollTop() > navHeight) {
                jQuery('#mainnav-inner').addClass('fixed-main-menu');
            }
            else {
                jQuery('#mainnav-inner').removeClass('fixed-main-menu');
            }
        });
    });
</script>

<script type="text/javascript">
    //<![CDATA[
    (function($) {
        jQuery( document ).ready(function( $ ) {
            if (($('#jm-col1 .block-account').length > 0)&($(window).width()<968)){
                $('#jm-quickaccess .shop-access').hide();
                $('#jm-col1 .block-account').clone().prependTo($('#jm-quickaccess .inner-toggle'));
            }
            $(window).resize(function(){
                if (!$('#jm-quickaccess .block-account').length){
                    if (($('#jm-col1 .block-account').length > 0)&($(window).width()<968)){
                        $('#jm-quickaccess .shop-access').hide();
                        $('#jm-col1 .block-account').clone().prependTo($('#jm-quickaccess .inner-toggle'));
                    }
                }
            });
        });

        $("#jm-head #jm-quickaccess,#jm-setting").mouseenter(function (){
            $(this).children().addClass("active");
            if ($(window).width()<462){
                //$("#jm-header").css("z-index",1000); //this code effect to mobile
            }

        }).mouseleave(function (){
            //$("#jm-header").css("z-index",""); //this code effect to mobile
            $(this).children().removeClass("active");

        });
        $("#jm-search,#jm-mycart").mouseenter(function(){
            if(!$(this).siblings(".inner-toggle").hasClass("active")) {
                //$("#jm-header").css("z-index",1000);
                $(this).children().addClass("active");
            }

        }).mouseleave(function(){
            if($(this).children(".inner-toggle").hasClass("active")) {
                $("#jm-header").css("z-index","");
                $(this).children().removeClass("active")
            }

        });

        $("#jm-quickaccess .btn-toggle").hover(function(e){
            $("#jm-quickaccess").toggleClass("active");
            if($("#jm-quickaccess").hasClass("active")){
                if(window.myaccountIScrol !== undefined && window.myaccountIScrol !== null){
                    window.myaccountIScrol.destroy();
                    window.myaccountIScrol  = null;
                }
                if($("#myaccountscroll").length){
                    windowheight = $(window).height()-$("#jm-head").height();
                    windowheight = windowheight - parseInt($("#jm-quickaccess .inner-toggle").css("padding-top"));
                    if($("#jm-quickaccess .inner-toggle").height() > windowheight){
                        $("#myaccountscroll").css("height",windowheight);
                    }
                    setTimeout(function(){
                        window.myaccountIScrol = new iScroll("myaccountscroll",{vScrollbar: true, useTransform: true,hScrollbar: false});
                    },100);
                }else{
                    quickaccess = $("#jm-quickaccess .inner-toggle").html();
                    myaccount = $('<div class="inner-togglecontent" />').append($("#jm-quickaccess .inner-toggle").html());
                    myaccount.css({float:"left",height:"auto"});
                    $("#jm-quickaccess .inner-toggle").html("");
                    myaccountscroll = $('<div id="myaccountscroll" />');
                    myaccount.appendTo(myaccountscroll);

                    windowheight = $(window).height()-$("#jm-head").height();
                    windowheight = windowheight - parseInt($("#jm-quickaccess .inner-toggle").css("padding-top"));
                    myaccountscroll.appendTo($("#jm-quickaccess .inner-toggle"));

                    setTimeout(function(){
                        if($("#jm-quickaccess .inner-toggle").height() > windowheight){
                            myaccountscroll.css("height",windowheight);
                            window.myaccountIScrol = new iScroll("myaccountscroll",{vScrollbar: true, useTransform: true,hScrollbar: false});
                            window.myaccountIScrol.refresh();
                        }

                    },100);

                }


            }

        });
    })(jQuery);
    //]]>
</script>