<?php
/*!
 * Theme Name: JM Team
 * Theme URI: http://www.joomlart.com
 * Version: 1.0
 * Description:
 * Author: JM Team - Joomlart.com
 * Author URI: http://www.joomlart.com
 *
 * Powered by Magento
 * Licensed under the Apache License v2.0
 * http://www.apache.org/licenses/LICENSE-2.0
 * Template for Mage_Page_Block_Html
 */
?>
<div class="main">
	<div class="inner clearfix">
		<!-- BEGIN: WELCOME -->
		<div class="jm-tl-head">
			<div class="jm-datetime" style="display: none">
				<i class="fa fa-clock-o"></i>
				<script>
					var date= new Date();
					var dayweek =["Воскресенье","Понедельник","Вторник","Среда","Четверг","Пятница","Суббота"][date.getDay()];
					var month =["Ян","Фв","Мар","Ап","Май","Июнь","Июль","Ав","Сен","Ок","Ноя","Дек"][date.getMonth()];
					var day = date.getDate();
					document.write(dayweek+", "+month+" "+day);
				</script>

			</div>

            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top-menu-left')->toHtml(); ?>
			<div class="welcome-msg">
				<?php echo $this->getChildHtml('welcome') ?> <?php echo $this->getAdditionalHtml() ?>
			</div>
		</div>
		<!-- END: WELCOME -->

		<!-- BEGIN: QUICK ACCESS -->
		<div id="jm-quickaccess" class="quick-access has-toggle">
			<div class="btn-toggle quickaccess-toggle">
				<i class="fa fa-user"></i><strong><?php echo $this->__('My Account') ?></strong>
			</div>
			<div class="inner-toggle">
				<div class="shop-access">
					<?php
					if($this->getChildHtml('customer_account_navigation')):
						echo $this->getChildHtml('customer_account_navigation');
					endif;
					?>
					<?php echo $this->getChildHtml('topLinks');  ?>

				</div>
				<?php
				$devicedetect = Mage::helper ('jmbasetheme/mobiledetect');

				?>
			</div>
		</div>
		<!-- END: QUICK ACCESS -->
		<!-- BEGIN: QUICK ACCESS -->
		<div id="jm-setting" class="quick-setting has-toggle">
			<div class="btn-toggle setting-toggle">
				<i class="fa fa-globe"></i><strong><?php echo $this->__('Setting') ?></strong>
			</div>
			<div class="inner-toggle">
				<?php echo $this->getChildHtml('store_language') ?>
				<?php echo $this->getChildHtml('custom_currency_selector') ?>
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('colors')->toHtml() ?>
			</div>
		</div>
		<!-- END: QUICK ACCESS -->

	</div>
</div>

